### PR TITLE
Added highlighting of read messages

### LINKED ISSUE #6: Unread emails.
Gmail activity doesn't difference between read and unread emails, unread emails should be shown in a different color (like the web client).

Gmail activity:
Screenshot1

Gmail web client:
Screenshot2

### PR DESCRIPTION
**Pull request by kipply**
Adds functionality that sets the background color of unread messages to white. Fixes #6 

Should I also include setting the email as read when opened, or should that go in another pull request?

### CODE REVIEW

**Comment by cvgarciarea** [comment]
Please, do not include setting emails as read when opened, that's another issue.
Whatever, github says there is a conflict with your branch at client.py file.

**Comment by kipply** [comment]
@cristian99garcia I've removed the commit. I'll be opening a new PR for that ~

**Comment by cvgarciarea** [comment]
I'm getting this now:

> Traceback (most recent call last):
  File "/home/broot/sugar-build/activities/gmail-activity/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/broot/sugar-build/activities/gmail-activity/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0
Traceback (most recent call last):
  File "/home/broot/sugar-build/activities/gmail-activity/canvas.py", line 138, in __logged_cb
    self.client.load()
  File "/home/broot/sugar-build/activities/gmail-activity/client.py", line 85, in load
    )['threads']]
KeyError: 'threads'

**Comment by kipply** [comment]
@cristian99garcia I believe the issue was that 'threads' would not be a key should the query return nothing. I've used `.get` to handle that. I'll also squash the last two commits~

**Pull request merged**
