### PR TITLE
Make left side buttons work

### LINKED ISSUE #13: Left section is currently useless.
Until now, left Gmail activity section is useless, it should work like it does in gmail web client.

Gmail activity:
Gmail activity left section

Gmail web client:
Gmail web client left section

### PR DESCRIPTION
**Pull request by kipply**
fixes #13

Note that this merge will make #3 more urgent, as now spam/trash emails are being added in too.

### CODE REVIEW

**Comment by cvgarciarea** [comment]
Ok, I was reviewing the wrong branch for 30 minutes...

It seems that it does everything it should do, but probably we want this functionality works with only one click.
Can you change this line? you should set it to "Gdk.EventType.BUTTON_PRESS"  https://github.com/kipply/gmail-activity/blob/master/mails_listbox.py#L71

**Comment by cvgarciarea** [comment]
I'm having the following error now, for opening the activity for the second time (probably, after clicking on a category item).
The mails list is empty.

> Traceback (most recent call last):
>   File "/home/broot/sugar-build/activities/gmail-activity/mails_listbox.py", line 218, in set_threads
>     self.threads_notebook.listboxes[tab].set_threads(threads[tab])
>   File "/home/broot/sugar-build/activities/gmail-activity/mails_listbox.py", line 152, in set_threads
>     if not thread["read"]:
> KeyError: 'read'

**Comment by kipply** [comment]
@cristian99garcia haha sorry about the extra branch lying on the repo

I changed the clicking, though I think that error should be impossible with the current master branch, as at line 150 it's `if thread["UNREAD"]:`

**Comment by cvgarciarea** [comment]
Thanks @kipply

**Pull request merged**
