### PR TITLE
Fix send button

### LINKED ISSUE #17: Send emails is broken.
Clicking on "Send" button (tested by send it to only one person), shows the following error.
Note: this error is only shown when you try to send an email in a new thread, answering a existing thread works fine.

```
Traceback (most recent call last):
  File "/home/broot/sugar-build/activities/gmail-activity/redactor.py", line 545, in _send_cb
    mail["raw"] = base64.urlsafe_b64encode(message.as_string())
  File "/usr/lib64/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib64/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib64/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib64/python2.7/email/generator.py", line 164, in _write_headers
    v, maxlinelen=self._maxheaderlen, header_name=h).encode()
  File "/usr/lib64/python2.7/email/header.py", line 410, in encode
    value = self._encode_chunks(newchunks, maxlinelen)
  File "/usr/lib64/python2.7/email/header.py", line 370, in _encode_chunks
    _max_append(chunks, s, maxlinelen, extra)
  File "/usr/lib64/python2.7/email/quoprimime.py", line 97, in _max_append
    L.append(s.lstrip())
AttributeError: 'list' object has no attribute 'lstrip'
```

### PR DESCRIPTION
**Pull request by sahilsaha7773**
In Gmail activity clicking on "Send" button (tested by send it to only one person) throws an error.
In this PR I tried to fix the above mentioned error.
Fixes #17

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

I don't understand what the patch does, what the problem was, and why it happened.  See our [guide to commit messages](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).

Also, please don't mention GCI in commit messages.  It is not relevant to the history in the repository.  See [GCI 2018 background](https://wiki.sugarlabs.org/go/Google_Code_In_2018/background#Getting_help) for some narrative on this.

**Comment by quozl** [comment]
Fixes #17.

@sahilsaha7773, please don't use "Fixes #n" in the pull request title. GitHub does not respond correctly to this.

Instead, use "Fixes #n" in the pull request body or "Fixes $ (URL)" in the commit message, because up until this comment the issue has not been linked to the pull request in a way that would automatically close the issue on merge.

@Hrishi1999, please don't link an issue to a pull request; this doesn't automatically close the issue on merge.

**Comment by chimosky** [comment]
@quozl this should be put on hold as the port to `WebKit2` wasn't tested before merge and the activity is broken. See #30

**Comment by quozl** [comment]
@chimosky, I don't think it needs to be put on hold.  @sahilsaha7773 can, if they want, rebase against the new _master_ branch after the revert, and then test the fix on a distribution of Linux that still has the older WebKit API.  Ubuntu 16.04 is one such.

**Comment by rhl-bthr** [comment]
Stale

**Pull request closed without merging**
