### PR TITLE
Add starring feature

### PR DESCRIPTION
**Pull request by kipply**
This is what the code should look like, however the `'clicked'` callback sometimes fails to work. Could you check to see if it's just an issue on my end (I've already found some anomalies in my setup)

I've tried moving the contents of `__favourite_clicked` into `__important_setted`, and all that functionality works fine. It seems that `__favourite_clicked` is just never reached.

### CODE REVIEW

**Comment by cvgarciarea** [comment]
Ok, this definitely does not work for me (I never receive the callback). I'm looking for an alternative, but nothing so far.

**Comment by kipply** [comment]
@cristian99garcia I'll try getting the `CellRendererFavourite` to extend `CellRendererToggle` instead of `CellRendererIcon`, though there's no reason that `clicked` shouldn't work.

**Comment by cvgarciarea** [comment]
Don't worry, I found a way to do it.
In a mix of internet examples, I made this:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import gi
gi.require_version("Gtk", "3.0")

from gi.repository import Gtk
from gi.repository import GObject


DESACTIVATED = "non-starred-symbolic"
ACTIVATED = "starred-symbolic"


class CellRendererPixbuf(Gtk.CellRendererPixbuf):

    __gsignals__ = {
        "clicked": (GObject.SIGNAL_RUN_LAST, GObject.TYPE_NONE, [str]),
    }

    def __init__(self):
        Gtk.CellRendererPixbuf.__init__(self)
        self.set_property("mode", Gtk.CellRendererMode.ACTIVATABLE)

    def do_activate(self, event, widget, path, background_area, cell_area, flags):
        self.emit("clicked", path)


class CellRendererPixbufWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="CellRendererPixbuf Example")

        self.set_default_size(200, 200)

        self.liststore = Gtk.ListStore(str, str)
        self.liststore.append(["Item 1", DESACTIVATED])
        self.liststore.append(["Item 2", DESACTIVATED])
        self.liststore.append(["Item 3", ACTIVATED])

        treeview = Gtk.TreeView(model=self.liststore)

        renderer_text = Gtk.CellRendererText()
        column_text = Gtk.TreeViewColumn("Text", renderer_text, text=0)
        treeview.append_column(column_text)

        renderer_pixbuf = CellRendererPixbuf()
        renderer_pixbuf.connect("clicked", self._clicked_cb)

        column_pixbuf = Gtk.TreeViewColumn("Image", renderer_pixbuf, icon_name=1)
        treeview.append_column(column_pixbuf)

        self.add(treeview)

    def _clicked_cb(self, cell, path):
        state = self.liststore[path][1]
        if state == ACTIVATED:
            self.liststore[path][1] = DESACTIVATED

        else:
            self.liststore[path][1] = ACTIVATED


win = CellRendererPixbufWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

**Comment by kipply** [comment]
@cristian99garcia Thanks, though I figured out the issue and I've amended my commit! 

It seems like while sugar's `CellRendererIcon` could emit `clicked`, it was never programmed properly to do so (I reviewed the code)

**Pull request merged**
